### ISSUE TITLE
SQL Query OLE DB not detected after latest update

### ISSUE THREAD

**Issue by jannepn** [MPCatalog/scom-community-catalog#11]
In latest release of the Query Ole DB monitor the monitor MP has been removed.
https://github.com/UretzkyZvi/Monitor-Applications-Using-SQL-Queries/issues/2

And when that MP is not installed it wont get detected by the Community Management pack.

Also the version number is incorrect it should be 1.0.0.1 (for QueryOleDbMonitorLibrary) or 2.0.0.5 if you target the QueryOleDbMonitorTemplate

**Comment by P2P-Nathan** [comment]
Thank you for the feedback, it's much appreciated.

I'll work at getting the catalog entries corrected.

Thanks,
Nathan

**Comment by P2P-Nathan** [comment]
Pull Request #31 resolves this issue.
