### ISSUE TITLE
SCOM.Alert.Tasks - new MP for share

### ISSUE THREAD

**Issue by msalomoun** [MPCatalog/scom-community-catalog#124]
#### New Packs
- The SCOM Management pack to add some alert tasks to SCOM console to get information about monitor/rule overidable parameters, its settings and so on. 
- SCOM.Alert.Tasks
- SCOM Alert Tasks
- 1.0.0.5
- https://github.com/msalomoun/SCOM.Alert.Tasks

**Comment by AnEvilPenguin** [comment]
resolved in #132 

Thanks for sharing!
