### ISSUE TITLE
New managementpacks

### ISSUE THREAD

**Issue by jannepn** [MPCatalog/scom-community-catalog#15]
Not an issue but a tip.
Here are some tips for management packs that are missing from the database.

ID: Eaton.UPS.Monitoring
Name: Eaton UPS Monitoring
1.0.1.15
https://powerquality.eaton.com/Products-services/Power-Management/Software-Drivers/MS-SCOM-Management-Pack.asp

ID: DataCore.SANsymphonyV.Library
Name: DataCore SANsymphony-V Library
1.3.0.13123
https://www.datacore.com/solutions/by-virtualization-platform/Microsoft/system-center-monitoring-pack.aspx
Need license for the product

HewlettPackard.ProLiant.Monitored.Library
Hewlett-Packard ProLiant Monitored Library Management Pack
3.1.0.0
HewlettPackard.Servers.Library
Hewlett-Packard Servers Core Library
2.3.0.0
https://h20392.www2.hpe.com/portal/swdepot/displayProductInfo.do?productNumber=HPSCOMMP-P
Product #:
HPSCOMMP-P
Global Trade ID:
Z7550-63218
Version:
1.80
Software specification:
HPE ProLiant Management Pack for System Center Operations Manager (Z7550-01351.exe)
HPE BladeSystem Management Pack for Microsoft System Center Operations Manager (Z7550-01573.exe)

HPEnterpriseStorageLibraryMP
HPE Storage Library Management Pack for System Center
4.5.0.0
https://h20392.www2.hpe.com/portal/swdepot/displayProductInfo.do?productNumber=System_Center

**Comment by P2P-Nathan** [comment]
Thanks for the packs, I don't think I've heard of the Eaton pack before so it will be great to get that visibility.

**Comment by shadeon** [comment]
@jannepn The download links provided for the HP management packs all point to lower versions than the ones listed above,  Are these now being bundled with another HP download/product, or located from another source?

**Comment by P2P-Nathan** [comment]
@jannepn , did you get an opportunity to reply to @shadeon with possible updated links?  The packs would be good to include in the catalog, but I wanted to confirm the version above was the correct one.

**Comment by jannepn** [comment]
@shadeon & @P2P-Nathan  HP are not very good at setting version number on their products. The MP:s are bundled with the HP oneview pack and that have one version number that is stated on the page. After installing the file from the page you can find the MP:s with the correct version numbers.

Here is an instruction for the storage pack:
http://www.mrchiyo.com/installing-and-configuring-hp-storage-management-pack-v4-2-1/

I could not find any instructions for the Proliant.
This is a older one:
http://kevingreeneitblog.blogspot.se/2011/07/scom-installing-hp-proliant-server.html

**Comment by jannepn** [comment]
All Managementpacks added
