### ISSUE TITLE
Improve contribution guidelines on the Wiki

### ISSUE THREAD

**Issue by shadeon** [MPCatalog/scom-community-catalog#16]
It would be great if the Wiki could be extended with some contribution guidelines and/or any criteria that must be met for a PR to be accepted.

For example, I hear the index.json file needs to be alphabetically sorted - if this is the case it should probably be stated so moderators don't need to comment on most PRs if the author didn't happen to naturally do this.

**Comment by shadeon** [comment]
Just to let you know I've started to write up the steps required to contribute to the repository using VSCode and git (on windows).  I can't submit a PR for the Wiki, but will post my text here for your review, and then you can either use this as a base or copy wholesale to the wiki if you like it 😄 

These steps are likely to be the one's i'll provide on the [Coffee Break](https://squaredup.com/coffee-break-series) so would appreciate your feedback either way!

**Comment by P2P-Nathan** [comment]
That sounds great.

I am working on instructions for making quick edits and adjustments on the
GitHub site, for those that just want to correct a version or MP name.
Hopefully as simple as Edit File > New Branch > New PR, with a couple
screenshots.  I'm hoping the whole process to make a simple update could be
30 seconds or so, then there will be very little friction for a user to
just update the version number or a simple spelling correction.

I'll combine both into the page once complete.

**Comment by shadeon** [comment]
Wasn't aware you could do it that way (without being a contributor), definitely the way to go for people making simple edits to existing content.

**Comment by shadeon** [comment]
Further documentation on contribution has been added, satisfies what I needed to know.
