### ISSUE TITLE
Renaming management packs

### ISSUE THREAD

**Issue by ehrnst** [MPCatalog/scom-community-catalog#42]
Hi,

Renaming management packs. Apart from all SCOM enivronments will have to delete and import the "new" MP. is there other potential issues?

**Comment by P2P-Nathan** [comment]
From the perspective of the catalog you would only need to rename the folder and update the index.  However, being that it has a new name, users of the old pack would not be notified of the update.

-Nathan

**Comment by Juanito99** [comment]
Lessons learned for the future: Need to think about a proper name from the beginning.

Would it be ok to add a new folder and keeping the old one for a while? 
I would add then an annotation in the notes that the MP was replaced by the other one.

**Comment by P2P-Nathan** [comment]
I have no objection to adding the updated pack as a new folder and including in the notes that the upgraded version requires a full re-install.

It is a little cumbersome, but I do not think we will need to do this too often.

**Comment by ehrnst** [comment]
i'm closing this issue for now. Thanks :)
