### ISSUE TITLE
New Management Pack found

### ISSUE THREAD

**Issue by Juanito99** [MPCatalog/scom-community-catalog#43]
### Is this issue related to a bug in the UI?
If yes, please [create a new issue in the UI repo](https://github.com/MPCatalog/scom-community-catalog-ui/issues/new)

### Have you included the following?
https://gallery.technet.microsoft.com/SCOM-Windows-Service-c9fc3f95?ranMID=24542&ranEAID=TnL5HPStwNw&ranSiteID=TnL5HPStwNw-1ye4S1MnAJaeunDQ7lQklg&tduid=(0cc497f76ce5c60d8f7081cd298077bf)(256380)(2459594)(TnL5HPStwNw-1ye4S1MnAJaeunDQ7lQklg)()

https://leibundgutski.wordpress.com/2017/02/19/scom-windows-service-monitor-management-pack/

#### New Packs
- [ x] A descriptive title: Service Monitoring
- [ ] MP SystemName
- [ ] MP Display Name
- [ ] MP Current Version
- [ ] MP Download URL

#### Pack Updates
- [ ] A descriptive title
- [ ] MP SystemName

**Comment by brandubh** [comment]
Guys for me this one is a no go, it monitors all the "automatic" services leading to a ton of alerts. This topic was debated more than 10 years ago with the SCOM team, it makes no sense to monitor all services, you must know what you're monitoring. immo.

**Comment by P2P-Nathan** [comment]
I second @brandubh, monitoring all "automatic" services is not likely to show many alerts of value.  Some services also have a setting of automatic but only run when they have work to do.

An additional note I would like to add, using a script, PS or VB, is additional overhead and in this case does not provide any value.  If you would like to monitor a large number of services efficiently, and without the template classes, you could do so watching for event 7024 and 7043 in the system log, using the schedule filter built into SCOM.

**Comment by P2P-Nathan** [comment]
Hello @Juanito99, thank you for sending over this pack.  After taking a look at how it works, I think this configuration may not be beneficial in most environments, the large scope of monitoring all automatic services could create a high volume of alerts without much value.

I've closed this request, as it does not look like a good fit for the catalog.
Thanks again for your submission,
Nathan

**Comment by Leibundgut** [comment]
Just an FYI, the MP doesn't use a script to monitor and it doesn't monitor "all automatic" services. It uses the same monitoring workflow as the built in SCOM service monitoring template to monitor the services. It only uses a script to discover the specific services you want to monitor (runs across all servers once a day) and it has an ok(ish) GUI to add/remove which specific services you would like monitored and what days/times of the week they should be monitored. I also made it so when you choose to monitor all startup types it disregards disabled services (unlike the default SCOM monitoring). it also has nice features like auto or manual restart logic (with excessive restart detection).

I don't think you looked at this close enough and gave it a fair shake, its not perfect but its way better and faster to setup than the default template monitoring.

Kevin explains how it works better than I do in my own blog, maybe read through his to get a better understanding or actually import it and use it and maybe you'll reconsider its usefulness. Thanks!

http://kevingreeneitblog.blogspot.com/2017/04/scom-new-community-mp-for-monitoring.html

**Comment by P2P-Nathan** [comment]
@goot1981, Thanks for the update.

I'll re-look at the pack.  The initial concern was that a user may add the pack as-is and get excessive monitoring/alerting.

Thanks,
Nathan
