### ISSUE TITLE
New MP found: AD Directory Services Addendum Management Pack

### ISSUE THREAD

**Issue by Juanito99** [MPCatalog/scom-community-catalog#54]
Hi guys,

I think the following is worth to be added:
https://gallery.technet.microsoft.com/SCOM-AD-Directory-Addendum-22d0473a

Thanks :)

Ruben

**Comment by P2P-Nathan** [comment]
Thanks for the update Ruben,

I'll take a look at this pack and add it to the catalog.

-Nathan

**Comment by Juanito99** [comment]
Perhaps we could try to engage him more. - He's frequently authoring MPs :-)

**Comment by P2P-Nathan** [comment]
Pull #59 includes this pack in the catalog.
