### ISSUE TITLE
Nice MP found - Agent Management

### ISSUE THREAD

**Issue by Juanito99** [MPCatalog/scom-community-catalog#64]
Hi,

found "Agent Management" which helps to add or remove Management Groups. 
It sill works in SCOM 1801; just tested :smile: 

Details here: 
[URL](https://blogs.technet.microsoft.com/jimmyharper/2016/08/13/scom-task-to-add-or-remove-management-groups-on-agents/)

Please add. Worth it.

**Comment by P2P-Nathan** [comment]
Thanks for the notice Ruben, I will take a look at getting the JSON updated
for this pack.

If you would like to submit a pull request with the updates I can approve
and merge it soon.

Thanks,
Nathan

**Comment by Juanito99** [comment]
Sorry, missed to update this issue. - Kevin Holman answered me on twitter, that he added Jimmy's stuff to the SCOM Management MP. - And the SCOM Management MP is already here in the mpcatalog :smile:
